# Generated by Django 4.2.13 on 2026-05-28 05:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel'), ('SAP_PROCUREMENT', 'SAP Procurement'), ('UTILITY_ELECTRICITY', 'Utility Electricity'), ('TRAVEL_FLIGHT', 'Travel - Flight'), ('TRAVEL_HOTEL', 'Travel - Hotel'), ('TRAVEL_GROUND', 'Travel - Ground')], max_length=30)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=10)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64)),
                ('row_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ingestion.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_index', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('parse_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.ingestionbatch')),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit', models.CharField(choices=[('KWH', 'kWh'), ('GJ', 'GJ'), ('LITERS', 'Liters'), ('KG', 'kg'), ('KM', 'km'), ('NIGHTS', 'Nights')], max_length=10)),
                ('quantity_co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('emission_factor_source', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('amount_local', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('flags', models.JSONField(default=dict)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('FLAGGED', 'Flagged'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingestion.datasource')),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized', to='ingestion.rawrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingestion.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='EditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edited_by', models.CharField(max_length=255)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('reason', models.TextField()),
                ('normalized_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='ingestion.normalizedrecord')),
            ],
        ),
        migrations.AddField(
            model_name='datasource',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='ingestion.tenant'),
        ),
    ]
